#%RAML 1.0 DataType 
type: object
properties:
  item_code:
    type: string
    example: code
    required: false
  item_date:
    type: datetime-only
    example: '2022-09-10T08:16:01'
    required: false
  item_id:
    type: string
    example: '0'
    required: false
  source_system:
    type: string
    example: source_systerm
    required: false
  gps_longitude:
    type: integer
    example: 0
    required: false
  reason_text:
    type: string
    example: rs_txt
    required: false
  reason_description:
    type: string
    example: reason_description
    required: false
  shipment_id:
    type: string
    example: shmt_id
    required: false
  reason_code:
    type: string
    example: rs_code
    required: false
  ids_value:
    type: string
    example: ids_value
    required: false
  capture_date:
    type: datetime-only
    example: '1970-01-01T19:10:25'
    required: false
  gps_latitude:
    type: integer
    example: 0
    required: false
  ids_type:
    type: string
    example: ids_type
    required: false
  item_description:
    type: string
    example: item_description
    required: false
